spring.datasource.url=jdbc:postgresql://localhost:5432/tgBotBase
spring.datasource.username=tgClient
spring.datasource.password=tgPass
telegram.bot.token=8864322092:AAG67-2y0gs7cTeVZxlh05sPa39Z2gcBmHE
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.enabled=true